name: SOAP
description: The Scanner Orchestration & Analysis Pipeline orchestrates multiple workflow scanning tools depending on the provided security level.

inputs:
  security_level:
    required: true
    type: choice
    options:
    - fundamental
    - essential
    - advanced

runs:
  using: 'composite'  
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set Versions and URLs
      run: |
        ACTIONLINT_VERSION="v0.0.4-soap"
        ACTIONLINT_PACKAGE_VERSION="${ACTIONLINT_VERSION#v}"

        POUTINE_VERSION="v0.0.2-soap"

        FRIZBEE_VERSION="v0.0.3-soap"
        FRIZBEE_PACKAGE_VERSION="${FRIZBEE_VERSION#v}"
        
        SEMGREP_VERSION="v0.1.1-soap"

        echo "ACTIONLINT_PACKAGE_VERSION=${ACTIONLINT_PACKAGE_VERSION}" >> $GITHUB_ENV
        echo "ACTIONLINT_URL=https://github.com/costrander6/actionlint-for-SOAP/releases/download/${ACTIONLINT_VERSION}/actionlint-for-SOAP_${ACTIONLINT_PACKAGE_VERSION}_linux_amd64.tar.gz" >> $GITHUB_ENV

        echo "POUTINE_VERSION=${POUTINE_VERSION}" >> $GITHUB_ENV
        echo "POUTINE_URL=https://github.com/costrander6/poutine-for-SOAP/releases/download/${POUTINE_VERSION}/poutine_Linux_x86_64.tar.gz" >> $GITHUB_ENV

        echo "FRIZBEE_PACKAGE_VERSION=${FRIZBEE_PACKAGE_VERSION}" >> $GITHUB_ENV
        echo "FRIZBEE_URL=https://github.com/costrander6/frizbee-for-SOAP/releases/download/${FRIZBEE_VERSION}/frizbee_${FRIZBEE_PACKAGE_VERSION}_linux_amd64.tar.gz" >> $GITHUB_ENV

        echo "SEM_URL=https://github.com/costrander6/semgrep-for-SOAP/releases/download/${SEMGREP_VERSION}/semgrep-1.164.0-cp310.cp311.cp312.cp313.cp314.py310.py311.py312.py313.py314-none-manylinux_2_34_x86_64.whl" >> $GITHUB_ENV
      shell: bash

    - name: Run actionlint
      run: |
        wget $ACTIONLINT_URL
        tar -xvf actionlint-for-SOAP_${ACTIONLINT_PACKAGE_VERSION}_linux_amd64.tar.gz
        ./actionlint-for-SOAP
      shell: bash

    - name: Run poutine
      run: |
        wget $POUTINE_URL
        tar -xvf poutine_Linux_x86_64.tar.gz
        ./poutine analyze_local .
      shell: bash

    - name: Run frizbee
      if: inputs.security_level == 'essential' || inputs.security_level == 'advanced'
      run: |
        wget $FRIZBEE_URL
        tar -xvf frizbee_${FRIZBEE_PACKAGE_VERSION}_linux_amd64.tar.gz
        ./frizbee actions .github/workflows --dry-run
      shell: bash

    - name: Run semgrep
      if: inputs.security_level == 'advanced'
      run: |
        sudo apt-get update
        sudo apt-get install -y libev4 libpcre3
        pip install $SEM_URL
        semgrep scan .github/workflows
      shell: bash
