name: SOAP
description: The Scanner Orchestration & Analysis Pipeline orchestrates multiple workflow scanning tools depending on the provided security level.

inputs:
  security_level:
    required: true
    type: choice
    options:
    - fundamental
    - essential
    - advanced
  target:
    required: false
    type: string
    default: '.github/workflows'

runs:
  using: 'composite'  
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set Versions and URLs
      run: |
        ACTIONLINT_VERSION="v1.7.12"
        ACTIONLINT_PACKAGE_VERSION="${ACTIONLINT_VERSION#v}"

        POUTINE_VERSION="v1.1.6"

        FRIZBEE_VERSION="v0.1.1-soap"
        FRIZBEE_PACKAGE_VERSION="${FRIZBEE_VERSION#v}"

        echo "ACTIONLINT_PACKAGE_VERSION=${ACTIONLINT_PACKAGE_VERSION}" >> $GITHUB_ENV

        echo "POUTINE_VERSION=${POUTINE_VERSION}" >> $GITHUB_ENV

        echo "FRIZBEE_PACKAGE_VERSION=${FRIZBEE_PACKAGE_VERSION}" >> $GITHUB_ENV
        echo "FRIZBEE_URL=https://github.com/costrander6/frizbee-for-SOAP/releases/download/${FRIZBEE_VERSION}/frizbee_${FRIZBEE_PACKAGE_VERSION}_linux_amd64.tar.gz" >> $GITHUB_ENV
      shell: bash

    - name: Run actionlint
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo rhysd/actionlint --pattern '*_linux_amd64.tar.gz' $ACTIONLINT_VERSION
        tar -xvf actionlint_${ACTIONLINT_PACKAGE_VERSION}_linux_amd64.tar.gz
        gh attestation verify -R rhysd/actionlint actionlint_${ACTIONLINT_PACKAGE_VERSION}_linux_amd64.tar.gz
        
        TARGET="${{ inputs.target }}"
        if [[ "$TARGET" != *.yml && "$TARGET" != *.yaml ]]; then
          TARGET="${TARGET%/}/*"
        fi

        echo "ACTIONLINT_SCAN_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
        ./actionlint -format "$(cat $GITHUB_ACTION_PATH/actionlint_soap_template.txt)" $TARGET > actionlint-out.json
      shell: bash

    - name: Run poutine
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo boostsecurityio/poutine --pattern 'poutine_Linux_x86_64.tar.gz' $POUTINE_VERSION
        tar -xvf poutine_Linux_x86_64.tar.gz

        TARGET="${{ inputs.target }}"
        TARGET="${TARGET%/}"

        if [[ "$TARGET" != ".github/workflows" ]]; then
          mkdir -p .github/workflows
          if [[ -f "$TARGET" ]]; then
            cp "$TARGET" .github/workflows/
          elif [[ -d "$TARGET" ]]; then
            cp "$TARGET"/* .github/workflows/
          else
            cp $TARGET .github/workflows/
          fi
        fi

        echo "POUTINE_SCAN_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
        ./poutine analyze_local . --format json --disable-version-check > poutine-out.json
      shell: bash

    - name: Run frizbee
      if: inputs.security_level == 'essential' || inputs.security_level == 'advanced'
      run: |
        wget $FRIZBEE_URL
        tar -xvf frizbee_${FRIZBEE_PACKAGE_VERSION}_linux_amd64.tar.gz
        echo "FRIZBEE_SCAN_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

        if [[ -f "$TARGET" ]]; then
          ./frizbee actions -no json "$TARGET" > frizbee-out.jsonl
        else
          ./frizbee actions -no json .github/workflows > frizbee-out.jsonl
        fi
      shell: bash

    - name: Run semgrep
      if: inputs.security_level == 'advanced'
      run: |
        sudo apt-get update
        sudo apt-get install -y libev4 libpcre3
        python3 -m pip install semgrep
        echo "SEMGREP_SCAN_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
        semgrep scan ${{ inputs.target }} --json-output=semgrep-out.json
      shell: bash

    - name: Export results
      run: |
        pip install pydantic
        python3 $GITHUB_ACTION_PATH/scripts/export-results.py $ACTIONLINT_SCAN_TIMESTAMP $POUTINE_SCAN_TIMESTAMP -f $FRIZBEE_SCAN_TIMESTAMP -s $SEMGREP_SCAN_TIMESTAMP
      shell: bash
