name: Run SOAP on SOAP
on:
    workflow_dispatch:
        inputs:
            security_level:
                required: true
                type: choice
                options:
                - fundamental
                - essential
                - advanced
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
        - main

jobs:
    run-soap:
        runs-on: ubuntu-latest
        steps:
            - uses: costrander6/SOAP@17022f03bc74d62d35dd9fad5068d0dbc39bd72e # v4.0.0
              with:
                security_level: ${{ github.event_name == 'pull_request' && 'advanced' || inputs.security_level }}

            - name: Read scanner output
              run: |
                echo actionlint; cat actionlint-out.json <(echo)
                echo poutine; cat poutine-out.json <(echo)
                echo frizbee; cat frizbee-out.json <(echo)
                echo semgrep; cat semgrep-out.json <(echo)