name: Run SOAP on SOAP
on:
    workflow_dispatch:
        inputs:
            security_level:
                required: true
                type: choice
                options:
                - fundamental
                - essential
                - advanced
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
        - main

jobs:
    run-soap:
        runs-on: ubuntu-latest
        steps:
            - uses: costrander6/SOAP@4368a28c77910b01e2415ad910df846f1b0f8e89 # v2.2.0
              with:
                security_level: ${{ github.event_name == 'pull_request' && 'advanced' || inputs.security_level }}